### ISSUE TITLE
How to create an undo/redo button in the menubar

### ISSUE THREAD

**Issue by damianthekreeeytor** [bangle-io/bangle.dev#142]
Just wondering the best way possible to include a undo and redo button.

**Comment by kepta** [comment]
Hey @damianthekreeeytor the [customizing menu items](https://bangle.dev/docs/examples/react-floating-menu/#customizing-menu-buttons) example shows how to add the UI for a button. Most of the icon's SVG in this library have been taken from https://css.gg. 

Regarding actually executing the undo redo, you can look at calling the undo , redo commands in the [history component](https://bangle.dev/docs/api/core/#history-component). Let me know if this helps.
