### ISSUE TITLE
Read only mode.

### ISSUE THREAD

**Issue by damianthekreeeytor** [bangle-io/bangle.dev#150]
Is it possible to carry over the styles for the markup in the editor to a view only mode? When I export the styles to HTML for example I see it still has the classes but the styles only take effect when opened in the editor.

**Comment by kepta** [comment]
I guess if you keep add the classes `ProseMirror bangle-editor` to your HTML it should work. The idea here is that if you get your output to have a similar structure as the live editable bangle Dom tree, the CSS  should style it similar.

Here is how the editable tree looks like:

<img width="538" alt="image" src="https://user-images.githubusercontent.com/6966254/112739086-25c30880-8f26-11eb-958a-639baf391e78.png">

**Comment by kepta** [comment]
Closing this for now, feel free to continue he discussion in https://github.com/bangle-io/bangle.dev/discussions
