### ISSUE TITLE
CSS is overriding margin for all h1/h2

### ISSUE THREAD

**Issue by mattcasey** [bangle-io/bangle.dev#159]
Not sure if this is a feature request or a bug, and it's easily addressed but this library removes the margin on all header tags on the page. Is it possible to add the .bangle-editor as a prefix to all tags here?
https://github.com/bangle-io/bangle.dev/blob/master/core/style.css#L29

**Comment by kepta** [comment]
That looks like a bug.

**Comment by kepta** [comment]
Thanks for the PR <3
