### ISSUE TITLE
Jump to start / end of heading 

### ISSUE THREAD

**Issue by kepta** [bangle-io/bangle.dev#171]
Since heading component doesn't have a child `paragraph` the `ctrl-a` (jump to start) and `ctrl-e` (jump to end) fall back to native behavior which doesn't work well. We need to implement something similar to what we have done for `paragraph` (see https://github.com/kepta/bangle-play/blob/72c2647dbc57faf464de43182c69cfcf91dc175b/core%2Fcomponents%2Fparagraph.js#L107).

**Comment by lucywang000** [comment]
> fall back to native behavior which doesn't work well.

I have tried using ctrl-a/ctrl-e on a h1 node and it works fine in all chrome/ff/safari. Could you provide more details?

**Comment by kepta** [comment]
if you add an inline node say an `emoji` or an `image` inside of a heading, jumping to start or end breaks.
