### ISSUE TITLE
Convert URL's to links

### ISSUE THREAD

**Issue by clibu** [bangle-io/bangle.dev#186]
When a user types a url ``http:\\fred.com`` or ``www.fred.com`` change into a link.

**Comment by lucywang000** [comment]
@kepta I think we need to introduce a new "link" node type to the schema, right?

**Comment by kepta** [comment]
We already have a link _mark_ and we should using an Input rule to add this mark to a matching link text. The closes I can think of is how [emoji suggest](https://bangle.dev/docs/examples/react-emoji-suggest) adds the `trigger` mark when pressed `:`.
