### ISSUE TITLE
How to use without build tool?

### ISSUE THREAD

**Issue by 1upkd** [bangle-io/bangle.dev#243]
Is it possible to setup bangle without any build tool, by directly including via a script tag in the HTML code? Ideally something like `<script src="bangle.js></script>`. 

I know it's 2021 but I happen to be a minimalist and prefer not to use build tools wherever possible.

**Comment by kepta** [comment]
I think you can use the ESM syntax to import the modules directly with the help of a CDN like https://www.skypack.dev , but I haven't really tested it out.

**Comment by 1upkd** [comment]
Thanks, will try it out :D
